INTCONCEPTO_MAP = {
    "COMISION 1ER AÑO": 1,
    "COMISION RENOVACION": 2,
    "DESPAGO COMISION POLIZA NUEVA": 3,
    "DESPAGO COMISION RENOVACION": 4,
    "PENDIENTE": None,
    "CANCELADO": None,
}

REPORTE_FINAL_MAP = {
    "COMISION 1ER AÑO": "SI",
    "COMISION RENOVACION": "SI",
    "DESPAGO COMISION POLIZA NUEVA": "SI",
    "DESPAGO COMISION RENOVACION": "SI",
    "PENDIENTE": "NO",
    "CANCELADO": "NO",
}